// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSi.UsersService.Database;

#nullable disable

namespace PhotoSi.UsersService.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PhotoSi.UsersService.Models.ShipmentAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShipmentAddresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2b51297-7948-4816-98da-e8502aba672e"),
                            City = "Roma",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "00100",
                            Street = "Via Roma 1"
                        },
                        new
                        {
                            Id = new Guid("e1d0862b-d5f8-426a-af8d-a05f03d3ea65"),
                            City = "Milano",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "20100",
                            Street = "Via Milano 2"
                        },
                        new
                        {
                            Id = new Guid("ad7ff260-682e-407e-86e5-e03891f100a4"),
                            City = "Napoli",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "80100",
                            Street = "Via Napoli 3"
                        });
                });

            modelBuilder.Entity("PhotoSi.UsersService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShipmentAddressId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentAddressId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d4bdc20-95dd-4fe3-98b3-ffac3eadae6d"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mario.rossi@gmail.com",
                            FirstName = "Mario",
                            LastName = "Rossi",
                            PhoneNumber = "+391234567890",
                            ProfilePictureUrl = "https://example.com/images/user01.jpg",
                            ShipmentAddressId = new Guid("f2b51297-7948-4816-98da-e8502aba672e"),
                            UserName = "User01"
                        },
                        new
                        {
                            Id = new Guid("dc1dc650-ee84-4f3d-9cca-a0baf9421d4e"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "luca.bianchi@gmail.com",
                            FirstName = "Luca",
                            LastName = "Bianchi",
                            PhoneNumber = "+391234567891",
                            ProfilePictureUrl = "https://example.com/images/user02.jpg",
                            ShipmentAddressId = new Guid("e1d0862b-d5f8-426a-af8d-a05f03d3ea65"),
                            UserName = "User02"
                        },
                        new
                        {
                            Id = new Guid("57b9385d-6b77-4db8-a1a0-510d54631257"),
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "giulia.verdi@gmail.com",
                            FirstName = "Giulia",
                            LastName = "Verdi",
                            PhoneNumber = "+391234567892",
                            ProfilePictureUrl = "https://example.com/images/user03.jpg",
                            ShipmentAddressId = new Guid("ad7ff260-682e-407e-86e5-e03891f100a4"),
                            UserName = "User03"
                        });
                });

            modelBuilder.Entity("PhotoSi.UsersService.Models.User", b =>
                {
                    b.HasOne("PhotoSi.UsersService.Models.ShipmentAddress", "ShipmentAddress")
                        .WithOne("User")
                        .HasForeignKey("PhotoSi.UsersService.Models.User", "ShipmentAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentAddress");
                });

            modelBuilder.Entity("PhotoSi.UsersService.Models.ShipmentAddress", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
