// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoSi.AddressBookService.Database;

#nullable disable

namespace PhotoSi.AddressBookService.Database.Migrations
{
    [DbContext(typeof(AddressBookDbContext))]
    [Migration("20250530090511_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PhotoSi.AddressBookService.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostalCode", "Street")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2b51297-7948-4816-98da-e8502aba672e"),
                            City = "Roma",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "00100",
                            Street = "Via Roma 1",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e1d0862b-d5f8-426a-af8d-a05f03d3ea65"),
                            City = "Milano",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "20100",
                            Street = "Via Milano 2",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ad7ff260-682e-407e-86e5-e03891f100a4"),
                            City = "Napoli",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "80100",
                            Street = "Via Napoli 3",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e72b435d-1adb-49e6-811a-77e53c211ff2"),
                            City = "Bologna",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "50100",
                            Street = "Via Bologna 4",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4e0b628f-89f6-4b30-a2a3-c5ee53af9882"),
                            City = "Torino",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "40100",
                            Street = "Via Torino 5",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("e9ad62c4-118a-4cb6-9493-5deeecfcd791"),
                            City = "Torino",
                            Country = "Italia",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "90100",
                            Street = "Via Genova 6",
                            Version = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
